Fix missing things from `main.py` example
Add missing abstract methods. Without this change we get errors that
look like:

```console
Traceback (most recent call last):
  File "/Users/sam/src/devlake/plugins/myplugin/myplugin/main.py", line 24, in <module>
    MyPlugin.start()
  File "/Users/sam/Library/Caches/pypoetry/virtualenvs/myplugin-wjMzsRW6-py3.11/lib/python3.11/site-packages/pydevlake/plugin.py", line 211, in start
    plugin = cls()
             ^^^^^
TypeError: Can't instantiate abstract class myplugin with abstract methods domain_scopes, remote_scope_groups, remote_scopes, tool_scope_type
```

Seems like `poetry` expects a shebang and for this to be executable.
Without this change we get errors that look like:

```console
poetry run myplugin/main.py --help

[Errno 8] Exec format error: 'myplugin/main.py'
```